drop table if exists users;
drop table if exists movieGenre;
drop table if exists movieRating;
drop table if exists movieDirector;
drop table if exists movieAwards;
drop table if exists movieActor;
drop table if exists Movies;
drop table if exists Actor;
drop table if exists Awards;
drop table if exists Director;
drop table if exists Genre;
drop table if exists Rating;

-- Admin and User tables

create table users (
    user_username varchar(255) not null,
    user_password varchar(255) not null,
    user_role varchar(255) not null,
    primary key (user_username)
);

insert into users (user_username, user_password, user_role) values
    ("admin", "password", "admin"),
    ("user", "password", "user");

-- Moive tables

create table Actor (
    actor_ID int auto_increment,
    actor_firstname varchar(255),
    actor_lastname varchar(255),
    actor_age int,
    actor_net_worth int,
    primary key (actor_ID)
);

create table Awards (
    award_ID int auto_increment,
    award_name varchar(255),
    primary key (award_ID)
);

create table Director (
    director_ID int auto_increment,
    director_firstname varchar(255),
    director_lastname varchar(255),
    director_age int,
    primary key (director_ID)
);

create table Genre (
    genre_ID int auto_increment,
    genre_title varchar(255),
    primary key (genre_ID)
);

create table Rating (
    rating_ID int auto_increment,
    rating_IMDB DOUBLE,
    rating_Rotten_Tomatoes DOUBLE,
    rating_Metacritic DOUBLE,
    primary key (rating_ID)
);

create table Movies (
    movie_ID int auto_increment,
    movie_title varchar(255),
    release_date date,
    duration int,
    synopsis varchar(4096),
    primary key (movie_ID)
);

create table movieGenre (
    movieGenre_ID int auto_increment,
    movie_ID int,
    genre_ID int,
    primary key (movieGenre_ID),
    foreign key (movie_ID) references Movies(movie_ID) on delete cascade,
    foreign key (genre_ID) references Genre(genre_ID) on delete cascade
);

create table movieRating (
    movieRating_ID int auto_increment,
    movie_ID int,
    rating_ID int,
    primary key (movieRating_ID),
    foreign key (movie_ID) references Movies(movie_ID) on delete cascade,
    foreign key (rating_ID) references Rating(rating_ID) on delete cascade
);

create table movieDirector (
    movieDirector_ID int auto_increment,
    movie_ID int,
    director_ID int,
    primary key (movieDirector_ID),
    foreign key (movie_ID) references Movies(movie_ID) on delete cascade,
    foreign key (director_ID) references Director(director_ID) on delete cascade
);

create table movieAwards (
    movieAwards_ID int auto_increment,
    movie_ID int,
    award_ID int,
    primary key (movieAwards_ID),
    foreign key (movie_ID) references Movies(movie_ID) on delete cascade,
    foreign key (award_ID) references Awards(award_ID) on delete cascade
);

create table movieActor (
    movieActor_ID int auto_increment,
    movie_ID int,
    actor_ID int,
    primary key (movieActor_ID),
    foreign key (movie_ID) references Movies(movie_ID) on delete cascade,
    foreign key (actor_ID) references Actor(actor_ID) on delete cascade
);

-- Triggers and Views and Logger

drop table if exists logger;
create table logger (
    logger_id int not null auto_increment,
    logger_operation varchar(255) not null,
    logger_table varchar(255) not null,
    logger_record_id int not null,
    logger_timestamp datetime default now(),
    primary key (logger_id)
);

drop view if exists movies_by_ID;
create view movies_by_ID as (
    select * from Movies
);

drop trigger if exists rating_update_trigger;
create trigger rating_update_trigger
after update on Rating
for each row
BEGIN 
    insert into logger(logger_operation, logger_table, logger_record_id) values
        ('UPDATE', 'Rating', new.rating_ID);
end;

drop trigger if exists rating_insert_trigger;
create trigger rating_insert_trigger
after update on Rating
for each row
BEGIN
    insert into logger(logger_operation, logger_table, logger_record_id) values
        ('INSERT', 'RATING', new.rating_ID);
end;



-- Inserts

insert into Actor (actor_firstname, actor_lastname, actor_age, actor_net_worth) values 
 ("Ewan","McGregor",51,25),
 ("Liam","Neeson",70,145),
 ("Natalie","Portman",41,90),
 ("Hayden","Christensen",41,12),
 ("Christopher ","Lee",93,25),
 ("Samuel L.","Jackson",73,250),
 ("Ian","McDiarmid",78,10),
 ("Jimmy","Smits",67,12),
 ("Frank","Oz",78,80),
 ("Mark","Hamill",71,18),
 ("Harrison","Ford",80,300),
 ("Carrie","Fisher",60,25),
 ("Daisy","Ridley",30,9),
 ("John","Boyega",30,8),
 ("Adam","Driver",39,16),
 ("Daniel","Radcliffe",33,110),
 ("Emma","Watson",32,85),
 ("Rupert","Grint",34,50),
 ("Bonnie ","Wright",31,4),
 ("Robert","Pattinson",36,100),
 ("Tom","Felton",35,20),
 ("Robert","Downey Jr.",57,300),
 ("Jon","Favreau",56,100),
 ("Gwyneth","Paltrow",50,250),
 ("Edward","Norton",53,300),
 ("Lou","Ferrigno",71,12),
 ("Tim","Roth",61,7),
 ("Mickey","Rourke",70,10),
 ("Chris","Hemsworth",39,130),
 ("Taika","Waititi",47,13),
 ("Chris","Evans",41,110),
 ("Hayley","Atwell",40,5),
 ("Sebastian","Stan",40,8),
 ("Elizabeth","Olsen",33,11),
 ("Scarlett","Johansson",38,165),
 ("Ben","Kingsley",78,60),
 ("Tom","Hiddleston",41,25),
 ("Sebastian","Stan",40,8),
 ("Anthony","Mackie",44,8),
 ("Chris","Pratt",43,80),
 ("Zoe","Saldana",44,35),
 ("Vin","Diesel",55,225),
 ("Paul","Rudd",53,70),
 ("Evangeline","Lilly",43,5),
 ("Michael","Douglas",78,350),
 ("Benedict","Cumberbatch",46,40),
 ("Rachel","McAdams",44,25),
 ("Benedict ","Wong",53,3),
 ("Kurt","Russell",71,100),
 ("Tom","Holland",26,25),
 ("Zendaya","",26,20),
 ("Michael","Keaton",71,40),
 ("Cate","Blanchett",53,95),
 ("Jeff","Goldblum",70,40),
 ("Chadwick","Boseman",43,4),
 ("Lupita","Nyong'o",39,10),
 ("Letitia","Wright",29,4),
 ("Josh","Brolin",54,45),
 ("Michelle","Pfeiffer",64,250),
 ("Brie","Larson",33,25),
 ("Park","Seo-joon",33,21),
 ("Gemma","Chan",40,6),
 ("Jake","Gyllenhaal",41,80),
 ("Florence","Pugh",26,8),
 ("David","Harbour",47,6),
 ("Simu ","Liu",33,4),
 ("Awkwafina","",34,8),
 ("Tony","Lengu Chiu-wai",60,20),
 ("Harry","Styles",28,100),
 ("Kit","Harrington",35,14),
 ("Angelina","Jolie",47,120),
 ("Tobey","Maguire",47,75),
 ("Xochitl","Gomez",16,1),
 ("Christian","Bale",48,120),
 ("Tenoch","Huerta",41,2),
 ("Michael","B. Jordan",35,25),
 ("Kirsten","Dunst",40,25),
 ("Willem","Dafoe",67,40),
 ("Alfred","Molina",69,10),
 ("Topher ","Grace",44,14);

insert into Awards (award_name) values
 ("Best Picture"),
 ("Best Director"),
 ("Best Actor"),
 ("Best Actress"),
 ("Best Cinematography"),
 ("Best Production Design"),
 ("Best Adapted Screenplay"),
 ("Best Sound"),
 ("Best Animated Short Film"),
 ("Best Live Action Short Film"),
 ("Best Film Editing"),
 ("Best Original Score"),
 ("Best Original Song"),
 ("Best Supporting Actor"),
 ("Best Supporting Actress"),
 ("Best Visual Effects"),
 ("Best Original Screenplay"),
 ("Best Documentary Short Film"),
 ("Best Documentary Feature Film"),
 ("Best International Feature Film"),
 ("Best Costume Design"),
 ("Best Makeup and Hairstyling"),
 ("Best Animated Feature"),
 ("Best Art Direction"),
 ("Special Achievement Awards");

insert into Director (director_firstname, director_lastname, director_age) values 
 ("George","Lucas","78"),
 ("J.J.","Abrams","56"),
 ("Rian","Johnson","48"),
 ("Chris","Columbus","64"),
 ("Alfonso","Cuaron","61"),
 ("Mike","Newell","80"),
 ("David","Yates","59"),
 ("Shane ","Black","60"),
 ("Jon","Favreau","56"),
 ("Louis","Leterrier","49"),
 ("Taika","Waititi","47"),
 ("Kenneth","Branagh","62"),
 ("Alan","Taylor","63"),
 ("Joe","Johnston","72"),
 ("Joss ","Whedon","58"),
 ("Shane ","Black","60"),
 ("Alan","Taylor","63"),
 ("Anthony ","Russo","52"),
 ("Joe","Russo","51"),
 ("James","Gunn","56"),
 ("Peyton","Reed","58"),
 ("Scott","Derrickson","56"),
 ("Jon","Watts","41"),
 ("Ryan","Coogler","36"),
 ("Anna ","Boden","43"),
 ("Ryan","Fleck","46"),
 ("Cate","Shortland","54"),
 ("Daniel","Cretton","44"),
 ("Chloe","Zhao","40"),
 ("Sam ","Raimi","63");

insert into Genre (genre_title) values
 ("Action"),
 ("Sci-Fi"),
 ("Adventure"),
 ("Fantasy"),
 ("Horror "),
 ("Comedy"),
 ("Crime and Mystery"),
 ("Historical "),
 ("Romance"),
 ("Satire"),
 ("Thriller"),
 ("Western"),
 ("Animation"),
 ("Drama"),
 ("Family"),
 ("Mystery"),
 ("Thriller");

insert into Rating (rating_IMDB, rating_Rotten_Tomatoes, rating_Metacritic) values
 (6.5,51,51),
 (6.6,65,54),
 (7.6,79,68),
 (8.6,93,90),
 (8.7,94,82),
 (8.3,83,58),
 (7.8,93,80),
 (6.9,91,84),
 (6.5,52,53),
 (7.6,81,65),
 (7.4,82,63),
 (7.4,82,63),
 (7.9,90,67),
 (7.5,78,71),
 (7.6,84,78),
 (7.7,77, null),
 (8.1,96,85),
 (7.9,94,79),
 (6.6,67,61),
 (6.9,71,57),
 (7,77,57),
 (6.9,79,66),
 (8,91,69),
 (7.1,79,62),
 (6.8,66,54),
 (7.8,90,70),
 (8,92,76),
 (7.3,76,66),
 (7.3,83,64),
 (7.8,90,75),
 (7.5,89,72),
 (7.6,85,67),
 (7.4,92,73),
 (7.9,93,74),
 (7.3,96,88),
 (8.4,85,68),
 (7,87,70),
 (6.8,79,64),
 (8.4,94,78),
 (7.4,90,69),
 (6.7,79,67),
 (7.4,91,71),
 (6.3,47,52),
 (8.3,93,71),
 (6.9,74,60),
 (6.3,64,57),
 (7.2,84,67),
 (7.4,90,73),
 (7.4,93,83),
 (6.3,63,59);

insert into Movies(movie_title, release_date, duration, synopsis) values 
 ("Star Wars: Episode I – The Phantom Menace","1999-05-19",136,"Obi-Wan Kenobi (Ewan McGregor) is a young apprentice Jedi knight under the tutelage of Qui-Gon Jinn (Liam Neeson) ; Anakin Skywalker (Jake Lloyd), who will later father Luke Skywalker and become known as Darth Vader, is just a 9-year-old boy. When the Trade Federation cuts off all routes to the planet Naboo, Qui-Gon and Obi-Wan are assigned to settle the matter."),
 ("Star Wars: Episode II - Attack of the Clones","2002-05-16",120,"Set ten years after the events of ""The Phantom Menace,"" the Republic continues to be mired in strife and chaos. A separatist movement encompassing hundreds of planets and powerful corporate alliances poses new threats to the galaxy that even the Jedi cannot stem. These moves, long planned by an as yet unrevealed and powerful force, lead to the beginning of the Clone Wars -- and the beginning of the end of the Republic."),
 ("Star Wars: Episode III – Revenge of the Sith","2005-05-19",140,"It has been three years since the Clone Wars began. Jedi Master Obi-Wan Kenobi (Ewan McGregor) and Jedi Knight Anakin Skywalker (Hayden Christensen) rescue Chancellor Palpatine (Ian McDiarmid) from General Grievous, the commander of the droid armies, but Grievous escapes. Suspicions are raised within the Jedi Council concerning Chancellor Palpatine, with whom Anakin has formed a bond. Asked to spy on the chancellor, and full of bitterness toward the Jedi Council, Anakin embraces the Dark Side."),
 ("Star Wars: Episode IV – A New Hope","1977-05-25",105,"The Imperial Forces -- under orders from cruel Darth Vader (David Prowse) -- hold Princess Leia (Carrie Fisher) hostage, in their efforts to quell the rebellion against the Galactic Empire. Luke Skywalker (Mark Hamill) and Han Solo (Harrison Ford), captain of the Millennium Falcon, work together with the companionable droid duo R2-D2 (Kenny Baker) and C-3PO (Anthony Daniels) to rescue the beautiful princess, help the Rebel Alliance, and restore freedom and justice to the Galaxy."),
 ("Star Wars: Episode V - The Empire Strikes Back","1980-05-21",124,"The adventure continues in this ""Star Wars"" sequel. Luke Skywalker (Mark Hamill), Han Solo (Harrison Ford), Princess Leia (Carrie Fisher) and Chewbacca (Peter Mayhew) face attack by the Imperial forces and its AT-AT walkers on the ice planet Hoth. While Han and Leia escape in the Millennium Falcon, Luke travels to Dagobah in search of Yoda. Only with the Jedi master's help will Luke survive when the dark side of the Force beckons him into the ultimate duel with Darth Vader (David Prowse)."),
 ("Star Wars: Episode VI - Return of the Jedi","1983-05-25",131,"Luke Skywalker (Mark Hamill) battles horrible Jabba the Hut and cruel Darth Vader to save his comrades in the Rebel Alliance and triumph over the Galactic Empire. Han Solo (Harrison Ford) and Princess Leia (Carrie Fisher) reaffirm their love and team with Chewbacca, Lando Calrissian (Billy Dee Williams), the Ewoks and the androids C-3PO and R2-D2 to aid in the disruption of the Dark Side and the defeat of the evil emperor."),
 ("Star Wars: The Force Awakens","2015-12-18",136,"Set thirty years after Return of the Jedi, The Force Awakens follows Rey, Finn, Poe Dameron, and Han Solo's search for Luke Skywalker and their fight in the Resistance, led by General Leia Organa and veterans of the Rebel Alliance, against Kylo Ren and the First Order, a successor to the Galactic Empire."),
 ("Star Wars: The Last Jedi","2017-12-15",152,"Luke Skywalker's peaceful and solitary existence gets upended when he encounters Rey, a young woman who shows strong signs of the Force. Her desire to learn the ways of the Jedi forces Luke to make a decision that changes their lives forever. Meanwhile, Kylo Ren and General Hux lead the First Order in an all-out assault against Leia and the Resistance for supremacy of the galaxy."),
 ("Star Wars: The Rise of Skywalker","2019-12-20",142,"When it's discovered that the evil Emperor Palpatine did not die at the hands of Darth Vader, the rebels must race against the clock to find out his whereabouts. Finn and Poe lead the Resistance to put a stop to the First Order's plans to form a new Empire, while Rey anticipates her inevitable confrontation with Kylo Ren."),
 ("Harry Potter and the Sorcerer's Stone","2001-11-14",167,"Adaptation of the first of J.K. Rowling's popular children's novels about Harry Potter, a boy who learns on his eleventh birthday that he is the orphaned son of two powerful wizards and possesses unique magical powers of his own. He is summoned from his life as an unwanted child to become a student at Hogwarts, an English boarding school for wizards. There, he meets several friends who become his closest allies and help him discover the truth about his parents' mysterious deaths."),
 ("Harry Potter and the Chamber of Secrets","2002-11-14",161,"The second instalment of boy wizard Harry Potter's adventures at Hogwarts School of Witchcraft and Wizardry, based on the novel by JK Rowling. A mysterious elf tells Harry to expect trouble during his second year at Hogwarts, but nothing can prepare him for trees that fight back, flying cars, spiders that talk and deadly warnings written in blood on the walls of the school."),
 ("Harry Potter and the Prisoner of Azkaban","2004-06-04",139,"Harry Potter's (Daniel Radcliffe) third year at Hogwarts starts off badly when he learns deranged killer Sirius Black (Gary Oldman) has escaped from Azkaban prison and is bent on murdering the teenage wizard. While Hermione's (Emma Watson) cat torments Ron's (Rupert Grint) sickly rat, causing a rift among the trio, a swarm of nasty Dementors is sent to protect the school from Black. A mysterious new teacher helps Harry learn to defend himself, but what is his secret tie to Sirius Black?"),
 ("Harry Potter and the Goblet of Fire","2005-11-18",157,"The fourth movie in the Harry Potter franchise sees Harry (Daniel Radcliffe) returning for his fourth year at Hogwarts School of Witchcraft and Wizardry, along with his friends, Ron (Rupert Grint) and Hermione (Emma Watson). There is an upcoming tournament between the three major schools of magic, with one participant selected from each school by the Goblet of Fire. When Harry's name is drawn, even though he is not eligible and is a fourth player, he must compete in the dangerous contest."),
 ("Harry Potter and the Order of the Phoenix","2007-07-11",138,"Now in his fifth year at Hogwarts, Harry (Daniel Radcliffe) learns that many in the wizarding community do not know the truth of his encounter with Lord Voldemort. Cornelius Fudge, minister of Magic, appoints his toady, Dolores Umbridge, as Defense Against the Dark Arts teacher, for he fears that professor Dumbledore will take his job. But her teaching is deficient and her methods, cruel, so Harry prepares a group of students to defend the school against a rising tide of evil."),
 ("Harry Potter and the Half-Blood Prince","2009-07-15",153,"As Death Eaters wreak havoc in both Muggle and Wizard worlds, Hogwarts is no longer a safe haven for students. Though Harry (Daniel Radcliffe) suspects there are new dangers lurking within the castle walls, Dumbledore is more intent than ever on preparing the young wizard for the final battle with Voldemort. Meanwhile, teenage hormones run rampant through Hogwarts, presenting a different sort of danger. Love may be in the air, but tragedy looms, and Hogwarts may never be the same again."),
 ("Harry Potter and the Deathly Hallows – Part 1","2010-11-19",146,"Without the guidance and protection of their professors, Harry (Daniel Radcliffe), Ron (Rupert Grint) and Hermione (Emma Watson) begin a mission to destroy the Horcruxes, the sources of Voldemort's immortality. Though they must rely on one another more than ever, dark forces threaten to tear them apart. Voldemort's Death Eaters have seized control of the Ministry of Magic and Hogwarts, and they are searching for Harry -- even as he and his friends prepare for the ultimate showdown."),
 ("Harry Potter and the Deathly Hallows: Part 2","2011-07-15",130,"A clash between good and evil awaits as young Harry (Daniel Radcliffe), Ron (Rupert Grint) and Hermione (Emma Watson) prepare for a final battle against Lord Voldemort (Ralph Fiennes). Harry has grown into a steely lad on a mission to rid the world of evil. The friends must search for the Horcruxes that keep the dastardly wizard immortal. Harry and Voldemort meet at Hogwarts Castle for an epic showdown where the forces of darkness may finally meet their match."),
 ("Iron Man","2008-05-02",126,"A billionaire industrialist and genius inventor, Tony Stark (Robert Downey Jr.), is conducting weapons tests overseas, but terrorists kidnap him to force him to build a devastating weapon. Instead, he builds an armored suit and upends his captors. Returning to America, Stark refines the suit and uses it to combat crime and terrorism."),
 ("The Incredible Hulk","2008-06-13",112,"Scientist Bruce Banner (Edward Norton) desperately seeks a cure for the gamma radiation that contaminated his cells and turned him into The Hulk. Cut off from his true love Betty Ross (Liv Tyler) and forced to hide from his nemesis, Gen. Thunderbolt Ross (William Hurt), Banner soon comes face-to-face with a new threat: a supremely powerful enemy known as The Abomination (Tim Roth)."),
 ("Iron Man 2","2010-05-07",125,"With the world now aware that he is Iron Man, billionaire inventor Tony Stark (Robert Downey Jr.) faces pressure from all sides to share his technology with the military. He is reluctant to divulge the secrets of his armored suit, fearing the information will fall into the wrong hands. With Pepper Potts (Gwyneth Paltrow) and ""Rhodey"" Rhodes (Don Cheadle) by his side, Tony must forge new alliances and confront a powerful new enemy."),
 ("Thor","2011-05-02",114,"As the son of Odin (Anthony Hopkins), king of the Norse gods, Thor (Chris Hemsworth) will soon inherit the throne of Asgard from his aging father. However, on the day that he is to be crowned, Thor reacts with brutality when the gods' enemies, the Frost Giants, enter the palace in violation of their treaty. As punishment, Odin banishes Thor to Earth. While Loki (Tom Hiddleston), Thor's brother, plots mischief in Asgard, Thor, now stripped of his powers, faces his greatest threat."),
 ("Captain America: The First Avenger","2011-07-19",124,"It is 1941 and the world is in the throes of war. Steve Rogers (Chris Evans) wants to do his part and join America's armed forces, but the military rejects him because of his small stature. Finally, Steve gets his chance when he is accepted into an experimental program that turns him into a supersoldier called Captain America. Joining forces with Bucky Barnes (Sebastian Stan) and Peggy Carter (Hayley Atwell), Captain America leads the fight against the Nazi-backed HYDRA organization."),
 ("The Avengers","2012-05-04",143,"When Thor's evil brother, Loki (Tom Hiddleston), gains access to the unlimited power of the energy cube called the Tesseract, Nick Fury (Samuel L. Jackson), director of S.H.I.E.L.D., initiates a superhero recruitment effort to defeat the unprecedented threat to Earth. Joining Fury's ""dream team"" are Iron Man (Robert Downey Jr.), Captain America (Chris Evans), the Hulk (Mark Ruffalo), Thor (Chris Hemsworth), the Black Widow (Scarlett Johansson) and Hawkeye (Jeremy Renner)."),
 ("Iron Man 3","2013-05-03",130,"Plagued with worry and insomnia since saving New York from destruction, Tony Stark (Robert Downey Jr.), now, is more dependent on the suits that give him his Iron Man persona -- so much so that every aspect of his life is affected, including his relationship with Pepper (Gwyneth Paltrow). After a malevolent enemy known as the Mandarin (Ben Kingsley) reduces his personal world to rubble, Tony must rely solely on instinct and ingenuity to avenge his losses and protect the people he loves."),
 ("Thor: The Dark World","2013-11-08",112,"In ancient times, the gods of Asgard fought and won a war against an evil race known as the Dark Elves. The survivors were neutralized, and their ultimate weapon -- the Aether -- was buried in a secret location. Hundreds of years later, Jane Foster (Natalie Portman) finds the Aether and becomes its host, forcing Thor (Chris Hemsworth) to bring her to Asgard before Dark Elf Malekith (Christopher Eccleston) captures her and uses the weapon to destroy the Nine Realms -- including Earth."),
 ("Captain America: The Winter Soldier","2014-04-04",136,"After the cataclysmic events in New York with his fellow Avengers, Steve Rogers, aka Captain America (Chris Evans), lives in the nation's capital as he tries to adjust to modern times. An attack on a S.H.I.E.L.D. colleague throws Rogers into a web of intrigue that places the whole world at risk. Joining forces with the Black Widow (Scarlett Johansson) and a new ally, the Falcon, Rogers struggles to expose an ever-widening conspiracy, but he and his team soon come up against an unexpected enemy."),
 ("Guardians of the Galaxy","2014-08-01",122,"Brash space adventurer Peter Quill (Chris Pratt) finds himself the quarry of relentless bounty hunters after he steals an orb coveted by Ronan, a powerful villain. To evade Ronan, Quill is forced into an uneasy truce with four disparate misfits: gun-toting Rocket Raccoon, treelike-humanoid Groot, enigmatic Gamora, and vengeance-driven Drax the Destroyer. But when he discovers the orb's true power and the cosmic threat it poses, Quill must rally his ragtag group to save the universe."),
 ("Avengers: Age of Ultron","2015-05-01",141,"When Tony Stark (Robert Downey Jr.) jump-starts a dormant peacekeeping program, things go terribly awry, forcing him, Thor (Chris Hemsworth), the Incredible Hulk (Mark Ruffalo) and the rest of the Avengers to reassemble. As the fate of Earth hangs in the balance, the team is put to the ultimate test as they battle Ultron, a technological terror hell-bent on human extinction. Along the way, they encounter two mysterious and powerful newcomers, Pietro and Wanda Maximoff."),
 ("Ant-Man","2015-06-29",118,"Forced out of his own company by former protégé Darren Cross, Dr. Hank Pym (Michael Douglas) recruits the talents of Scott Lang (Paul Rudd), a master thief just released from prison. Lang becomes Ant-Man, trained by Pym and armed with a suit that allows him to shrink in size, possess superhuman strength and control an army of ants. The miniature hero must use his new skills to prevent Cross, also known as Yellowjacket, from perfecting the same technology and using it as a weapon for evil."),
 ("Captain America: Civil War","2016-05-06",148,"Political pressure mounts to install a system of accountability when the actions of the Avengers lead to collateral damage. The new status quo deeply divides members of the team. Captain America (Chris Evans) believes superheroes should remain free to defend humanity without government interference. Iron Man (Robert Downey Jr.) sharply disagrees and supports oversight. As the debate escalates into an all-out feud, Black Widow (Scarlett Johansson) and Hawkeye (Jeremy Renner) must pick a side."),
 ("Doctor Strange","2016-10-20",115,"Dr. Stephen Strange's (Benedict Cumberbatch) life changes after a car accident robs him of the use of his hands. When traditional medicine fails him, he looks for healing, and hope, in a mysterious enclave. He quickly learns that the enclave is at the front line of a battle against unseen dark forces bent on destroying reality. Before long, Strange is forced to choose between his life of fortune and status or leave it all behind to defend the world as the most powerful sorcerer in existence."),
 ("Guardians of the Galaxy Vol. 2","2017-05-05",137,"Peter Quill and his fellow Guardians are hired by a powerful alien race, the Sovereign, to protect their precious batteries from invaders. When it is discovered that Rocket has stolen the items they were sent to guard, the Sovereign dispatch their armada to search for vengeance. As the Guardians try to escape, the mystery of Peter's parentage is revealed."),
 ("Spider-Man: Homecoming","2017-07-07",133,"Thrilled by his experience with the Avengers, young Peter Parker returns home to live with his Aunt May. Under the watchful eye of mentor Tony Stark, Parker starts to embrace his newfound identity as Spider-Man. He also tries to return to his normal daily routine -- distracted by thoughts of proving himself to be more than just a friendly neighborhood superhero. Peter must soon put his powers to the test when the evil Vulture emerges to threaten everything that he holds dear."),
 ("Thor: Ragnarok","2017-11-03",130,"Imprisoned on the other side of the universe, the mighty Thor finds himself in a deadly gladiatorial contest that pits him against the Hulk, his former ally and fellow Avenger. Thor's quest for survival leads him in a race against time to prevent the all-powerful Hela from destroying his home world and the Asgardian civilization."),
 ("Black Panther","2018-02-16",135,"After the death of his father, T'Challa returns home to the African nation of Wakanda to take his rightful place as king. When a powerful enemy suddenly reappears, T'Challa's mettle as king -- and as Black Panther -- gets tested when he's drawn into a conflict that puts the fate of Wakanda and the entire world at risk. Faced with treachery and danger, the young king must rally his allies and release the full power of Black Panther to defeat his foes and secure the safety of his people."),
 ("Avengers: Infinity War","2018-04-27",149,"Iron Man, Thor, the Hulk and the rest of the Avengers unite to battle their most powerful enemy yet -- the evil Thanos. On a mission to collect all six Infinity Stones, Thanos plans to use the artifacts to inflict his twisted will on reality. The fate of the planet and existence itself has never been more uncertain as everything the Avengers have fought for has led up to this moment."),
 ("Ant-Man and the Wasp","2018-07-06",118,"Scott Lang is grappling with the consequences of his choices as both a superhero and a father. Approached by Hope van Dyne and Dr. Hank Pym, Lang must once again don the Ant-Man suit and fight alongside the Wasp. The urgent mission soon leads to secret revelations from the past as the dynamic duo finds itself in an epic battle against a powerful new enemy."),
 ("Captain Marvel","2019-03-08",124,"Captain Marvel is an extraterrestrial Kree warrior who finds herself caught in the middle of an intergalactic battle between her people and the Skrulls. Living on Earth in 1995, she keeps having recurring memories of another life as U.S. Air Force pilot Carol Danvers. With help from Nick Fury, Captain Marvel tries to uncover the secrets of her past while harnessing her special superpowers to end the war with the evil Skrulls."),
 ("Avengers: Endgame","2019-04-26",182,"Adrift in space with no food or water, Tony Stark sends a message to Pepper Potts as his oxygen supply starts to dwindle. Meanwhile, the remaining Avengers -- Thor, Black Widow, Captain America and Bruce Banner -- must figure out a way to bring back their vanquished allies for an epic showdown with Thanos -- the evil demigod who decimated the planet and the universe."),
 ("Spider-Man: Far from Home","2019-07-02",130,"Peter Parker's relaxing European vacation takes an unexpected turn when Nick Fury shows up in his hotel room to recruit him for a mission. The world is in danger as four massive elemental creatures -- each representing Earth, air, water and fire -- emerge from a hole torn in the universe. Parker soon finds himself donning the Spider-Man suit to help Fury and fellow superhero Mysterio stop the evil entities from wreaking havoc across the continent."),
 ("Black Widow","2021-07-09",113,"Natasha Romanoff, aka Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy, and the broken relationships left in her wake long before she became an Avenger."),
 ("Shang-Chi and the Legend of the Ten Rings","2021-09-03",132,"Martial-arts master Shang-Chi confronts the past he thought he left behind when he's drawn into the web of the mysterious Ten Rings organization."),
 ("Eternals","2021-11-05",157,"The Eternals, a race of immortal beings with superhuman powers who have secretly lived on Earth for thousands of years, reunite to battle the evil Deviants."),
 ("Spider-Man: No Way Home","2021-12-17",148,"With Spider-Man's identity now revealed, our friendly neighborhood web-slinger is unmasked and no longer able to separate his normal life as Peter Parker from the high stakes of being a superhero. When Peter asks for help from Doctor Strange, the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man."),
 ("Doctor Strange in the Multiverse of Madness","2022-05-06",126,"Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses, to battle multiple threats, including other-universe versions of himself, which threaten to wipe out millions across the multiverse."),
 ("Thor: Love and Thunder","2022-07-08",119,"Thor embarks on a journey unlike anything he's ever faced -- a quest for inner peace. However, his retirement gets interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods. To combat the threat, Thor enlists the help of King Valkyrie, Korg and ex-girlfriend Jane Foster, who -- to his surprise -- inexplicably wields his magical hammer. Together, they set out on a harrowing cosmic adventure to uncover the mystery of the God Butcher's vengeance."),
 ("Black Panther: Wakanda Forever","2022-11-11",161,"Queen Ramonda, Shuri, M'Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T'Challa's death. As the Wakandans strive to embrace their next chapter, the heroes must band together with Nakia and Everett Ross to forge a new path for their beloved kingdom."),
 ("Spider-Man","2002-05-03",121,"""Spider-Man"" centers on student Peter Parker (Tobey Maguire) who, after being bitten by a genetically-altered spider, gains superhuman strength and the spider-like ability to cling to any surface. He vows to use his abilities to fight crime, coming to understand the words of his beloved Uncle Ben: ""With great power comes great responsibility."""),
 ("Spider-Man 2","2004-06-30",135,"When a failed nuclear fusion experiment results in an explosion that kills his wife, Dr. Otto Octavius (Alfred Molina) is transformed into Dr. Octopus, a cyborg with deadly metal tentacles. Doc Ock blames Spider-Man (Tobey Maguire) for the accident and seeks revenge. Meanwhile, Spidey's alter ego, Peter Parker, faces fading powers and self-doubt. Complicating matters are his best friend's (James Franco) hatred for Spider-Man and his true love's (Kirsten Dunst) sudden engagement to another man."),
 ("Spider-Man 3","2007-05-04",139,"Peter Parker (Tobey Maguire) and M.J. (Kirsten Dunst) seem to finally be on the right track in their complicated relationship, but trouble looms for the superhero and his lover. Peter's Spider-Man suit turns black and takes control of him, not only giving Peter enhanced power but also bringing out the dark side of his personality. Peter must overcome the suit's influence as two supervillains, Sandman and Venom, rise up to destroy him and all those he holds dear.");

insert into movieGenre(movie_ID, genre_ID) values
 (1,1),
 (1,2),
 (1,3),
 (1,4),
 (2,1),
 (2,2),
 (2,3),
 (2,4),
 (2,1),
 (2,2),
 (2,3),
 (2,4),
 (3,1),
 (3,2),
 (3,3),
 (3,4),
 (4,1),
 (4,2),
 (4,3),
 (4,4),
 (5,1),
 (5,2),
 (5,3),
 (5,4),
 (6,1),
 (6,2),
 (6,3),
 (6,4),
 (7,1),
 (7,2),
 (7,3),
 (7,4),
 (8,1),
 (8,2),
 (8,3),
 (8,4),
 (9,1),
 (9,2),
 (9,3),
 (9,4),
 (10,3),
 (10,15),
 (10,4),
 (11,3),
 (11,15),
 (11,4),
 (11,16),
 (12,3),
 (12,15),
 (12,4),
 (12,16),
 (13,3),
 (13,15),
 (13,4),
 (13,16),
 (14,3),
 (14,15),
 (14,4),
 (14,16),
 (14,1),
 (15,3),
 (15,15),
 (15,4),
 (15,16),
 (15,1),
 (16,3),
 (16,15),
 (16,4),
 (16,16),
 (17,3),
 (17,15),
 (17,4),
 (17,16),
 (18,1),
 (18,3),
 (18,2),
 (19,1),
 (19,3),
 (19,2),
 (20,1),
 (20,3),
 (20,2),
 (21,1),
 (21,3),
 (21,4),
 (22,1),
 (22,2),
 (22,3),
 (23,1),
 (23,2),
 (23,3),
 (24,1),
 (24,2),
 (24,3),
 (25,1),
 (25,3),
 (25,4),
 (26,1),
 (26,3),
 (26,2),
 (26,17),
 (27,1),
 (27,2),
 (27,3),
 (27,6),
 (28,1),
 (28,2),
 (28,3),
 (29,1),
 (29,2),
 (29,3),
 (29,6),
 (30,1),
 (30,2),
 (30,3),
 (31,1),
 (31,2),
 (31,3),
 (31,4),
 (32,1),
 (32,2),
 (32,3),
 (32,6),
 (33,1),
 (33,2),
 (33,3),
 (34,1),
 (34,3),
 (34,6),
 (34,4),
 (34,2),
 (35,1),
 (35,2),
 (35,3),
 (36,1),
 (36,2),
 (36,3),
 (37,1),
 (37,2),
 (37,3),
 (37,6),
 (38,1),
 (38,2),
 (38,3),
 (39,1),
 (39,2),
 (39,3),
 (39,14),
 (40,1),
 (40,2),
 (40,3),
 (41,1),
 (41,2),
 (41,3),
 (42,1),
 (42,2),
 (42,3),
 (42,4),
 (43,1),
 (43,2),
 (43,3),
 (43,4),
 (44,1),
 (44,2),
 (44,3),
 (44,4),
 (45,1),
 (45,2),
 (45,3),
 (45,4),
 (45,5),
 (46,1),
 (46,2),
 (46,3),
 (46,4),
 (46,6),
 (46,9),
 (47,1),
 (47,2),
 (47,3),
 (47,4),
 (47,14),
 (47,17),
 (48,1),
 (48,2),
 (48,3),
 (49,1),
 (49,2),
 (49,3),
 (50,1),
 (50,2),
 (50,3);

insert into movieRating(movie_ID, rating_ID) values
 (1,1),
 (2,2),
 (3,3),
 (4,4),
 (5,5),
 (6,6),
 (7,7),
 (8,8),
 (9,9),
 (10,10),
 (11,11),
 (12,12),
 (13,13),
 (14,14),
 (15,15),
 (16,16),
 (17,17),
 (18,18),
 (19,19),
 (20,20),
 (21,21),
 (22,22),
 (23,23),
 (24,24),
 (25,25),
 (26,26),
 (27,27),
 (28,28),
 (29,29),
 (30,30),
 (31,31),
 (32,32),
 (33,33),
 (34,34),
 (35,35),
 (36,36),
 (37,37),
 (38,38),
 (39,39),
 (40,40),
 (41,41),
 (42,42),
 (43,43),
 (44,44),
 (45,45),
 (46,46),
 (47,47),
 (48,48),
 (49,49),
 (50,50);

insert into movieDirector(movie_ID, director_ID) values
 (1,1),
 (2,1),
 (3,1),
 (4,1),
 (5,1),
 (6,1),
 (7,2),
 (8,3),
 (9,2),
 (10,4),
 (11,4),
 (12,5),
 (13,6),
 (14,7),
 (15,7),
 (16,7),
 (17,7),
 (18,8),
 (18,9),
 (19,10),
 (20,9),
 (21,11),
 (21,12),
 (21,13),
 (22,14),
 (23,15),
 (24,16),
 (25,17),
 (26,18),
 (26,19),
 (27,20),
 (28,15),
 (29,21),
 (30,18),
 (30,19),
 (31,22),
 (32,20),
 (33,23),
 (34,11),
 (35,24),
 (36,18),
 (36,19),
 (37,21),
 (38,25),
 (38,26),
 (39,18),
 (39,19),
 (40,23),
 (41,27),
 (42,28),
 (43,29),
 (44,23),
 (45,30),
 (46,11),
 (47,24),
 (48,30),
 (49,30),
 (50,30);

insert into movieActor(movie_ID, actor_ID) values
 (1,1),
 (1,2),
 (1,3),
 (1,7),
 (1,6),
 (1,9),
 (2,1),
 (2,3),
 (2,4),
 (2,5),
 (2,7),
 (2,8),
 (2,9),
 (3,1),
 (3,3),
 (3,4),
 (3,5),
 (3,7),
 (3,8),
 (3,9),
 (4,10),
 (4,11),
 (4,12),
 (5,10),
 (5,11),
 (5,12),
 (6,10),
 (6,11),
 (6,12),
 (7,13),
 (7,14),
 (7,15),
 (8,13),
 (8,14),
 (8,10),
 (9,12),
 (9,10),
 (9,13),
 (10,16),
 (10,17),
 (10,18),
 (11,16),
 (11,17),
 (11,19),
 (12,16),
 (12,17),
 (12,18),
 (13,17),
 (13,16),
 (13,20),
 (14,16),
 (14,17),
 (14,18),
 (15,21),
 (15,16),
 (15,17),
 (16,16),
 (16,17),
 (16,22),
 (17,16),
 (17,17),
 (17,18),
 (18,23),
 (18,24),
 (18,25),
 (19,26),
 (19,27),
 (19,28),
 (20,23),
 (20,24),
 (20,29),
 (21,30),
 (21,3),
 (21,31),
 (22,32),
 (22,33),
 (22,34),
 (23,35),
 (23,36),
 (23,25),
 (24,23),
 (24,37),
 (24,24),
 (25,30),
 (25,3),
 (25,38),
 (26,39),
 (26,32),
 (26,40),
 (27,41),
 (27,42),
 (27,43),
 (28,23),
 (28,32),
 (28,36),
 (29,44),
 (29,45),
 (29,46),
 (30,32),
 (30,23),
 (30,40),
 (31,47),
 (31,48),
 (31,49),
 (32,41),
 (32,42),
 (32,50),
 (33,51),
 (33,52),
 (33,53),
 (34,54),
 (34,30),
 (34,55),
 (35,56),
 (35,57),
 (35,58),
 (36,23),
 (36,59),
 (36,30),
 (37,44),
 (37,45),
 (37,60),
 (38,61),
 (38,62),
 (38,63),
 (39,23),
 (39,32),
 (39,36),
 (40,51),
 (40,52),
 (40,64),
 (41,36),
 (41,65),
 (41,66),
 (42,67),
 (42,68),
 (42,69),
 (43,70),
 (43,71),
 (43,72),
 (44,51),
 (44,52),
 (44,73),
 (45,35),
 (45,48),
 (45,74),
 (46,30),
 (46,75),
 (46,3),
 (47,76),
 (47,77),
 (47,58),
 (48,78),
 (48,79),
 (48,80),
 (49,78),
 (49,79),
 (50,78),
 (50,79);

insert into movieAwards (movie_ID, award_ID) values
 ("4","24"),
 ("4","21"),
 ("4","11"),
 ("4","12"),
 ("4","8"),
 ("4","16"),
 ("5","8"),
 ("5","25"),
 ("6","25"),
 ("35","12"),
 ("35","21"),
 ("35","6"),
 ("49","16");
